[package]
name = "macboxx_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.153"
rdev = "0.5.3"
rust-ini = "0.21.0"
tempfile = "3.10.1"
unix-named-pipe = "0.2.0"
