[buttons]
A = 'j'
B = 'o'
X = 'k'
Y = '/'
Z = 'i'
START = 'return'
DPAD_UP = 'uparrow'
DPAD_DOWN = 'downarrow'
DPAD_LEFT = 'leftarrow'
DPAD_RIGHT = 'rightarrow'

[control_stick]
UP = 'w'
DOWN = 's'
LEFT = 'a'
RIGHT = 'd'

[c_stick]
UP = 'semicolon'
DOWN = 'comma'
LEFT = 'n'
RIGHT = 'l'

[triggers]
L = 'q'
R = 'space' 

[mods]
MOD_Y = 'shiftleft'
MOD_X = 'shiftright'
